#Coffee-Beans Dark
general {

	border_size = 3

	col.active_border = rgb(854719)
	col.inactive_border = rgb(d0ba97)

}

decoration {
	rounding = 10
	rounding_power = 2

	active_opacity = 1.0
	inactive_opacity = 0.95

	shadow {
		enabled = false
		range = 4
		render_power = 3
		color = rgb(e0d9d5)
	}

	blur {
		enabled = true
		size = 5
		passes = 1

		vibrancy = 0.1696
	}
}
exec = sleep 1 && /home/yk/Documents/Rice/Current/Wallpaper/dark.sh